export interface Graduate {
  id_number?: number,
  first_name?: string,
  mid_name?: string,
  last_name?: string,
  email?: string,
  mobile?: number,
  birthday?: string,
  course?: string,
  college?: string,
  affiliations?: string,
  awards?: string,
  motto?: string,
  package?: string,
  shoot_date?: string,
  time_period?: string,
  shoot_time?: string,
  receipt_details?: string,
  initial_payment?: number,
  balance?: number,
  agreed_to_rules?: boolean,
  approved?: boolean
}


      // idNo: ['', Validators.required],
      // name: ['', Validators.required],
      // email: ['', Validators.required],
      // mobile: ['', Validators.required],
      // birthday: [new Date('1992'), Validators.required],
      // course: ['', Validators.required],
      // college: ['', Validators.required],
      // affiliations: ['', Validators.required],
      // awards: ['', Validators.required],
      // motto: ['', Validators.required],
      // package: ['', Validators.required],
      // shootDate: [new Date(), Validators.required],
      // timePeriod: ['', Validators.required],
      // shootTime: ['', Validators.required],
      // receiptDetails: ['', Validators.required]
